---
# based on https://github.com/geerlingguy/ansible-role-mysql/blob/master/.travis.yml for now
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-role-common
  matrix:
    - MOLECULE_DISTRO: debian:9
    - MOLECULE_DISTRO: centos:7
    #- MOLECULE_DISTRO: ubuntu1804
    #- MOLECULE_DISTRO: ubuntu1604
    # - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install ansible molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  #- cd ../
  #- mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  #- cd geerlingguy.$ROLE_NAME
  - docker -v
  - id

script:
  # Run tests.
  - molecule converge || true
  - molecule test || true

#notifications:
#webhooks: https://galaxy.ansible.com/api/v1/notifications/