---
# install a list of packages for centos
- name: Enable epel repo
  yum:
    name: epel-release
    state: present

- name: Install common list of packages for Centos
  yum:
    name:
      - git
      - curl
      - wget
      - rsync
      - borgbackup
      - sudo
      - vim-enhanced
      - net-tools
      - htop
      - ncdu
      - tmux
      - smartmontools
      - bash-completion
      - cryptsetup
      - dnf-automatic
      - tcpdump
      - sysstat
      - mtr
      - traceroute
      - bind-utils
      - whois
      - zip
      - unzip
      - hdparm
      - udisks2
      - pciutils
      - usbutils
      - nfs-utils
      - dmidecode
      - lshw
      - strace
      - nmap
  # enable services
  notify:
    - 'enable dnf-automatic'
    - 'enable smartd'

- name: Configure yum-cron
  template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    backup: 'yes'
    owner: root
    group: root
    mode: 0644
