---
# this will create the same template file if I ever decide to run testing or sid again
# so this will need to be fixed some time
# ie look at templates/sourceslist.conf.j2
# sid and testing don't need backports and security
- name: Create sources.list file
  template:
   src: sourceslist.conf.j2
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  when:
   - not ansible_lsb.id == 'Raspbian'

- name: Create sources.list file for Raspbian
  template:
   src: sourceslist.raspbian.conf.j2
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  when:
   - ansible_lsb.id == 'Raspbian'

- name: Update cache
  apt:
   update_cache: 'yes'
   name:
    - aptitude
    - unattended-upgrades

- name: Run apt-get upgrade
  apt:
   upgrade: safe

- name: Remove apt package popularity-contest
  apt:
   name: popularity-contest
   state: absent

- name: Create unattended conf file
  template:
   src: 50unattended-upgrades.j2
   dest: /etc/apt/apt.conf.d/50unattended-upgrades
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  notify: restart unattended-upgrades

- name: Create unattended conf file to enable unattended-upgrades
  template:
   src: 20auto-upgrades.j2
   dest: /etc/apt/apt.conf.d/20auto-upgrades
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  notify: restart unattended-upgrades
