---
# this will create the same template file if I ever decide to run testing or sid again
# so this will need to be fixed some time
# ie look at templates/sourceslist.conf.j2
# sid and testing don't need backports and security
- name: Create sources.list file
  ansible.builtin.template:
   src: sourceslist.conf.j2
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  when:
   - not ansible_lsb.id == 'Raspbian'

- name: Create sources.list file for Raspbian
  ansible.builtin.template:
   src: sourceslist.raspbian.conf.j2
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  when:
   - ansible_lsb.id == 'Raspbian'

- name: Update cache
  ansible.builtin.apt:
   update_cache: 'yes'
   name:
    - aptitude
    - unattended-upgrades
    # add this package since in D11 unattended-upgrades is useless without it
    - powermgmt-base

- name: Run apt-get upgrade
  ansible.builtin.apt:
   upgrade: safe

- name: Remove apt package popularity-contest
  ansible.builtin.apt:
   name: popularity-contest
   state: absent

- name: Create unattended conf file
  ansible.builtin.template:
   src: 50unattended-upgrades.j2
   dest: /etc/apt/apt.conf.d/50unattended-upgrades
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  notify: 'Restart unattended-upgrades'

# I believe this is required since buster
# since I don't remember having this task for stretch
- name: Create unattended conf file to enable unattended-upgrades
  ansible.builtin.template:
   src: 20auto-upgrades.j2
   dest: /etc/apt/apt.conf.d/20auto-upgrades
   owner: root
   group: root
   mode: 0644
   backup: 'yes'
  notify: 'Restart unattended-upgrades'
