---
# keep this task file around for the time being if I need to reference
# Debian 9 packages
- name: Install common basic package list
  ansible.builtin.apt:
   install_recommends: 'no'
   name:
    - git
    - curl
    - wget
    - rsync
    - borgbackup
    - less
    - sudo
    - vim
    - net-tools
    - htop
    - ncdu
    - tmux
    - smartmontools
    - bash-completion
    - cryptsetup
    - apt-transport-https
    - apt-file
    - tcpdump
    - sysstat
    - mtr
    - traceroute
    - dnsutils
    - whois
    - zip
    - unzip
    - hdparm
    - udisks2
    - pciutils
    - usbutils
    - nfs-common
    - dmidecode
    - lshw
    - strace
    - netfilter-persistent
    - python3-pip
    - virtualenv
    - python3-virtualenv
    - python3-setuptools
    - virtualenv
    - gcc
    - lsb-release
    - nmap
    - iperf
    - netcat-openbsd
    # add jq for json parsing
    - jq
    - sshfs
  notify: 'Restart unattended-upgrades'
