---
- name: install common basic package list
  apt:
   name: "{{ packages}}"
   install_recommends: no
  vars:
   packages:
   - git
   - curl
   - wget
   - rsync
# not on deb8
   #- borgbackup
   - less
   - sudo
   - vim
   - net-tools
   - htop
   - ncdu
   - smartmontools
   - bash-completion
   - cryptsetup
   - apt-transport-https
   - apt-file
   - tcpdump
   - sysstat
   - mtr
   - traceroute
   - dnsutils
   - whois
   - zip
   - unzip
   - hdparm
   - udisks2
   - pciutils
   - usbutils
   - nfs-common
   - dmidecode
   - lshw
   - strace
  notify: restart unattended-upgrades
- name: install nmap without recommends
  apt:
   name: nmap
   install_recommends: no
- name: install borgbackup from backports
  apt:
   name: borgbackup
   default_release: jessie-backports

