---
- name: install common basic package list
  apt:
   install_recommends: 'no'
   name:
    - git
    - curl
    - wget
    - rsync
    - borgbackup
    - less
    - sudo
    - vim
    - net-tools
    - htop
    - ncdu
    - tmux
    - smartmontools
    - bash-completion
    - cryptsetup
    - apt-transport-https
    - apt-file
    - tcpdump
    - sysstat
    - mtr
    - traceroute
    - dnsutils
    - whois
    - zip
    - unzip
    - hdparm
    - udisks2
    # required for unlocking luks encrypted drives for udisks2
    # https://github.com/pop-os/pop/issues/163
    - libblockdev-crypto2
    # apparmor profiles
    - apparmor-profiles
    - pciutils
    - usbutils
    - nfs-common
    - dmidecode
    - lshw
    - strace
    - netfilter-persistent
    # tasty python
    - python3-pip
    - python3-virtualenv
    - python3-setuptools
    # gcc for pip
    - gcc
    # add rclone for backup
    - rclone
    # useful for ansible
    - lsb-release
    # nmap
    - nmap
    - iperf
    - netcat-openbsd
  notify: restart unattended-upgrades
