---
- name: Create sources.list file
  template:
   src: sourceslist.conf.j2
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: 0644
   backup: yes
  when:
   - not ansible_lsb.id == 'Raspbian'

- name: Create sources.list file for Raspbian
  template:
   src: sourceslist.raspbian.conf.j2
   dest: /etc/apt/sources.list
   owner: root
   group: root
   mode: 0644
   backup: yes
  when:
   - ansible_lsb.id == 'Raspbian'

- name: Update cache
  apt:
   update_cache: yes
   name: "{{ packages }}"
  vars:
   packages:
    - aptitude
    - unattended-upgrades

- name: run aptitude safe-upgrade
  # 2.4 doesn't need aptitude anymore, since it falls back to apt-get anyway
  # leaving it here, in case I use 2.2 on stretch
  apt:
   upgrade: safe

- name: Remove apt package popularity-contest
  apt:
   name: popularity-contest
   state: absent

- name: Create unattended conf file
  template:
   src: 50unattended-upgrades.j2
   dest: /etc/apt/apt.conf.d/50unattended-upgrades
   owner: root
   group: root
   mode: 0644
   backup: yes
  notify: restart unattended-upgrades
