---
# only run on debian
#- fail:
#   msg: "This is not a Debian system."
#  when: ansible_distribution != 'Debian'
# Include variables and define needed variables.
- name: Include my variables.
  include_vars: main.yml

- name: Include common templating for Debian
  include_tasks: "{{ ansible_distribution }}-common.yml"
  when:
    - ansible_distribution == 'Debian'

#- name: Include common templating for Debian
#  include_tasks: "{{ ansible_distribution }}-common.yml"
#  when:
#    - ansible_distribution == 'CentOS'

- name: Include overrides specific to Centos 7.
  include_tasks: "{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == "7"


- name: Include overrides specific to Debian 7.
  include_tasks: "{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "7"

- name: Include overrides specific to Debian 8.
  include_tasks: "{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "8"

- name: Include overrides specific to Debian 9.
  include_tasks: "{{ ansible_distribution }}-{{ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "9"

- name: Include overrides specific to Raspbian.
  include_tasks: "{{ ansible_lsb.id }}.yml"
  when: ansible_lsb.id == 'Raspbian'
