---

- name: Remove the default /etc/apt/sources.list.d/raspi.list
  file:
   dest: /etc/apt/sources.list.d/raspi.list
   state: absent

- name: Update apt cache
  apt:
   update_cache: 'yes'

# remove some packages
- name: Remove bluetooth packages
  apt:
   name:
    - bluez
    - bluez-firmware
    - triggerhappy
   state: absent
   autoremove: 'yes'
