---
- name: Restart unattended-upgrades
  ansible.builtin.service:
   name: unattended-upgrades
   state: restarted
   enabled: 'yes'
  listen: 'Restart unattended-upgrades'

- name: Enable yum-cron on CentOS 7
  ansible.builtin.service:
   name: yum-cron
   state: restarted
   enabled: 'yes'
  listen: "Enable yum-cron"

- name: Enable smartd
  ansible.builtin.service:
   name: smartd
   state: restarted
   enabled: 'yes'
  listen: "Enable smartd"

- name: Enable dnf-automatic on CentOS 8
  ansible.builtin.service:
   name: dnf-automatic
   state: restarted
   enabled: 'yes'
  listen: "Enable dnf-automatic"
