---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian_9
    image: debian:9

# debian 7 & 8 are too bothersome to test due to old repos being moved to debian archive

  - name: centos_7
    image: centos:7
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
